### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by luizpicolo** [luizpicolo/siai-ifms-na#1]
- [x] Testes automatizados para gerenciamento de usuários
 - [x] Testes automatizados para gerenciamento de senhas
 - [x] Testes automatizados para gerenciamento de estudantes
 - [x] Gerenciamento para cursos
 - [ ] Testes automatizados para acesso e restrições 
 - [ ] Adicionar [SweetAlert](https://github.com/sharshenov/sweetalert-rails)
 - [ ] Melhorias no designer responsivo
 - [ ] Documentação
